version: "3.7"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: npm run dev --host 0.0.0.0 --port 8080
    ports:
      - "8080:5173"
